### ISSUE TITLE
Dynamic library dependencies with mismatched versions--suggestions?

### ISSUE THREAD

**Issue by LoonSongSoftware** [lueschem/edi-raspbian#7]
In general, the system works very well, and this isn't really a bug report; it's a request for comment on best practice.

**Here's the issue:**
I'm compiling a Raspbian-targeted application that depends on `libudev-dev`, which requires `libudev1`. This is a core library for Ubuntu and Raspbian (so lots of applications, like `apt`, break when this library gets screwed up). My understanding is that, for multiarch installations, the versions of each architecture must be identical. Here are the available versions as reported by `sudo apt list libudev1`:
`libudev1/stable,now 241-7~deb10u5 amd64 [installed]`
`libudev1/stable 241-7~deb10u5+rpi1 armhf`

So the versions are different by the "+rpi1".

**Question**:
What is the best practice for dealing with a situation like this? (If I just force the installation of the armhf version, it breaks the machine (no availability of `apt;` lots of other amd64 applications/libraries are removed.)
*  Copy the relevant files (`libudev1`, `libudev-dev` include files, etc.) from a Raspbian machine into the corresponding armhf directories on the edi machine? (Lots of manual work and/or creating a script to do all the stuff that the package installer usually does.)
* Try to compile new version(s)--amd64 and armhf of the libraries, so I can do a `make install`? (This seems fraught and likely to result in similar 'damage' to `libudev1`-dependent packages.)
* Some other way? (There must be a better way???)

How do you deal with this situation when library versions are substantially identical, but not exactly so? If you have a good answer, it might be worth a blog post.

**Comment by lueschem** [comment]
Many thanks for your detailed description!
I also came across this +rpi1 issue several times and luckily there is a workaround that I described here:
https://www.get-edi.io/Cross-Compiling-for-Raspbian-Buster/ (Dealing with +rpi1 Issues).

After all, the situation is not really convenient. This is due to the mixed Raspberry Pi OS/Debian setup. The good thing is that this might improve as soon as Raspberry Pi OS also gets widely adopted for arm64. The arm64 variant of Raspberry Pi OS uses the official Debian packages and therefore you get rid of the +rpi1 issue.

Another possible approach that might work for some projects is to use a pure Debian on the target device (such as https://github.com/lueschem/edi-pi). Like this you also get rid of the +rpi1 issue but the binaries are then not fully compatible with Raspberry Pi OS and the resulting images/binaries will not run on the Raspberry Pi editions with the BCM2835 CPU.

**Comment by LoonSongSoftware** [comment]
Thank you! I feel like an idiot, because I had seen that post--even skimmed the bit about having to compile certain mismatched versions--but didn't recognize that it was **exactly responsive** to my problem.

Unfortunately, I do have a mixed environment that includes both BCM2835s (old RPis) and newer ones.

So I guess I'll start recompiling (as you suggest) some of the core libraries.

Thanks again!

**Comment by LoonSongSoftware** [comment]
Forgot to "Close with comment."

As always, read the docs! (Or the blog more carefully, as the case may be.)
